LOG_FILE = 'log.txt'

# Connection parameters
ACCESS_KEY_ID = None
SECRET_ACCESS_KEY = None
ATHENA_GARBAGE_PATH = '<ATHENA_OUTPUT_LOCATION>'
WORKGROUP = '<WORKGROUP>'
REGION = '<REGION>'
DATABASE = '<DATABASE>'

# Database Parameters
DATABASE_BUCKET = '<DATABASE_BUCKET>'
DATABASE_ROOT_KEY = 'dedupe/'
BUFFERSIZE = 100000
