language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests, e.g. python setup.py test
#script:  PLEASE CHANGE ME
